#!/usr/bin/env bash
# =============================================================================
# run-docker.sh — Run Character Vault using Docker (Apache + PHP)
#
# USAGE:
#   ./run-docker.sh [OPTIONS]
#
# OPTIONS:
#   -p, --port <port>   Host port to expose (default: 8080)
#   -d, --dir <path>    Path to the extracted artifact directory
#                       (default: latest entry in dist/)
#   --no-cache          Force rebuild of the run image (ignore Docker layer cache)
#   -h, --help          Show this help and exit
#
# DESCRIPTION:
#   Builds a minimal Docker image (php:8.3-apache + pdo_sqlite + mod_rewrite)
#   the first time, then mounts the artifact and starts the container.
#   The image is cached as 'character-vault-run:latest' for subsequent runs.
#
#   The container uses the .htaccess file generated by scripts/build.sh to route
#   /api/* to the PHP backend and all other requests to the SvelteKit SPA.
#
# PREREQUISITES:
#   - Docker Engine (any recent version with BuildKit)
#   - An artifact produced by scripts/build.sh or scripts/build-docker.sh
# =============================================================================

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
die()     { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PORT=8080
APP_DIR=""
NO_CACHE=""
RUN_IMAGE="character-vault-run:latest"

# ── Argument parsing ──────────────────────────────────────────────────────────
usage() { grep '^# ' "$0" | sed 's/^# //'; exit 0; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        -p|--port)    PORT="$2";           shift 2 ;;
        -d|--dir)     APP_DIR="$2";        shift 2 ;;
        --no-cache)   NO_CACHE="--no-cache"; shift ;;
        -h|--help)    usage ;;
        *) die "Unknown option: $1  (use --help for usage)" ;;
    esac
done

# ── Check Docker ──────────────────────────────────────────────────────────────
command -v docker &>/dev/null \
    || die "'docker' not found. Install Docker from https://docs.docker.com/get-docker/"

# ── Locate the artifact ───────────────────────────────────────────────────────
if [[ -z "$APP_DIR" ]]; then
    DIST_DIR="${SCRIPT_DIR}/dist"
    [[ -d "$DIST_DIR" ]] \
        || die "No dist/ directory found. Run ./scripts/build.sh (or build-docker.sh) first."

    APP_DIR="$(find "$DIST_DIR" -maxdepth 1 -mindepth 1 -type d \
                   -name 'character-vault-*' \
               | sort | tail -1)"

    [[ -n "$APP_DIR" ]] \
        || die "No artifact found in dist/. Run ./scripts/build.sh first."
fi

APP_DIR="$(cd "$APP_DIR" && pwd)"   # absolute path (required for Docker bind mount)

[[ -d "${APP_DIR}/api" ]]   || die "Malformed artifact: missing api/ in ${APP_DIR}"
[[ -d "${APP_DIR}/build" ]] || die "Malformed artifact: missing build/ in ${APP_DIR}"

# ── Build the run image (only if needed or --no-cache) ───────────────────────
# The image is intentionally minimal: php:8.3-apache + pdo_sqlite + mod_rewrite.
# It is tagged 'character-vault-run:latest' and reused on subsequent runs.
IMAGE_EXISTS=false
docker image inspect "$RUN_IMAGE" &>/dev/null && IMAGE_EXISTS=true

if [[ "$IMAGE_EXISTS" == false || -n "$NO_CACHE" ]]; then
    echo ""
    info "Building run image (${RUN_IMAGE}) — this takes ~1 minute the first time…"

    # Write a temporary Dockerfile
    TMP_CTX="$(mktemp -d /tmp/character-vault-docker-XXXXXX)"
    trap 'rm -rf "$TMP_CTX"' EXIT

    cat > "${TMP_CTX}/Dockerfile" <<'DOCKERFILE'
FROM php:8.3-apache

# Install pdo_sqlite (compiled from source — included in the official image)
RUN docker-php-ext-install pdo pdo_sqlite \
    # Enable Apache mod_rewrite for .htaccess routing
    && a2enmod rewrite \
    # Allow .htaccess overrides in the document root
    && sed -i \
        's|<Directory /var/www/html>|<Directory /var/www/html>\n    AllowOverride All|' \
        /etc/apache2/sites-available/000-default.conf

WORKDIR /var/www/html
DOCKERFILE

    docker build ${NO_CACHE} -t "$RUN_IMAGE" "${TMP_CTX}"
    rm -rf "$TMP_CTX"
    trap - EXIT
    success "Run image built: ${RUN_IMAGE}"
else
    success "Using cached run image: ${RUN_IMAGE}"
fi

# ── Determine the version tag from the VERSION file ───────────────────────────
APP_VERSION="$(cat "${APP_DIR}/VERSION" 2>/dev/null || echo "dev")"

# ── Launch the container ──────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}════════════════════════════════════════════════════${RESET}"
echo -e "${BOLD}  Character Vault — Docker run${RESET}"
echo -e "${BOLD}════════════════════════════════════════════════════${RESET}"
info "Artifact  : ${APP_DIR}"
info "Version   : ${APP_VERSION}"
info "Image     : ${RUN_IMAGE}"
info "Address   : http://localhost:${PORT}"
echo ""
echo -e "  Press ${BOLD}Ctrl+C${RESET} to stop."
echo ""

# Run with:
#   - artifact mounted read-only at the document root
#   - APP_ENV set to production (can be overridden with -e)
#   - database written inside the container at /var/lib/character-vault/
# Note: the SQLite database path in production is /var/lib/character-vault/database.sqlite
# (defined in api/config.php). To persist across container restarts, mount a volume there.
docker run --rm \
    --name "character-vault-run" \
    -v "${APP_DIR}:/var/www/html:ro" \
    -v "character-vault-db:/var/lib/character-vault" \
    -e "APP_ENV=production" \
    -p "${PORT}:80" \
    "$RUN_IMAGE"
