/**
 * @file pipeline.ts
 * @description Mathematical pipeline types: Modifiers, StatisticPipeline, SkillPipeline,
 *              and ResourcePool.
 *
 * Design philosophy:
 *   EVERYTHING that can be calculated is a Pipeline. Strength, Armour Class, Initiative,
 *   Land Speed, Jump modifier, current HP — all are pipelines. This uniformity means:
 *     1. The engine has one code path for any stat: sum active modifiers, apply stacking rules.
 *     2. Any modifier can target any pipeline by its `ID`, including future homebrew stats.
 *     3. The UI always reads the same shape of data.
 *
 *   THE THREE-PHASE MODIFIER LIFECYCLE:
 *     1. PASSIVE (activeModifiers):
 *        Modifiers that are always "on" when the feature is active (e.g., +2 STR from a Belt).
 *        These feed into `totalBonus` and `totalValue` shown on the character sheet.
 *
 *     2. CONDITIONAL (activeModifiers with `conditionNode`):
 *        Modifiers that are only active when a runtime condition is met.
 *        Example: Monk AC bonus (WIS mod to AC, but only without armour/shield/load).
 *        These are evaluated at sheet-computation time (every time the DAG reruns).
 *        If the condition is TRUE → they join `activeModifiers` totals.
 *        If the condition is FALSE → they are ignored.
 *
 *     3. SITUATIONAL (situationalModifiers with `situationalContext`):
 *        Modifiers that only apply at DICE ROLL TIME, against a specific target context.
 *        Example: Ranger's Favoured Enemy (+2 attack/damage vs Orcs).
 *        These are NEVER added to `totalBonus` on the sheet.
 *        The Dice Engine reads `situationalModifiers`, matches `situationalContext`
 *        against the roll's `RollContext.targetTags`, and adds matched bonuses to
 *        `RollResult.situationalBonusApplied`.
 *
 * @see src/lib/types/primitives.ts  for ID, ModifierType
 * @see src/lib/types/i18n.ts        for LocalizedString
 * @see src/lib/types/logic.ts       for LogicNode
 * @see src/lib/utils/stackingRules.ts (Phase 2.4) for stacking resolution
 * @see src/lib/utils/diceEngine.ts    (Phase 2.5) for situational bonus evaluation
 */

import type { ID, ModifierType } from './primitives';
import type { LocalizedString } from './i18n';
import type { LogicNode } from './logic';

// =============================================================================
// MODIFIER — The atomic unit of change
// =============================================================================

/**
 * A single modifier that adjusts a pipeline's value.
 *
 * Modifiers are ALWAYS sourced from a Feature (race, class, feat, item, spell, etc.).
 * They are never generated by the engine itself — the engine only reads and aggregates them.
 *
 * KEY FIELD: `situationalContext`
 *   If this field is present, the modifier is SITUATIONAL and is NEVER counted in
 *   `totalBonus`. It lives in `StatisticPipeline.situationalModifiers` instead.
 *   This is the core mechanism for Favoured Enemy, flanking bonuses, etc.
 *
 * KEY FIELD: `conditionNode`
 *   If this field is present, the modifier is CONDITIONAL. The engine evaluates
 *   the node at sheet-computation time. Only if the condition is TRUE does the
 *   modifier count toward `totalBonus`.
 *
 * KEY FIELD: `value`
 *   Can be a number (most common) OR a formula string (e.g., "@attributes.stat_wis.derivedModifier").
 *   String values are resolved by the Math Parser at computation time.
 *   This enables data-driven cross-stat dependencies:
 *     - Monk WIS → AC
 *     - Paladin CHA → saves
 *     - Psionic manifester level formulas
 *
 * @example Flat numerical modifier (Ring of Protection +2):
 * ```json
 * {
 *   "id": "mod_ring_protection_ac",
 *   "sourceId": "item_ring_of_protection_2",
 *   "sourceName": { "en": "Ring of Protection +2" },
 *   "targetId": "combatStats.ac_normal",
 *   "value": 2,
 *   "type": "deflection"
 * }
 * ```
 *
 * @example Formula-as-value modifier (Monk WIS to AC):
 * ```json
 * {
 *   "id": "mod_monk_wis_ac",
 *   "sourceId": "class_feature_monk_ac_bonus",
 *   "sourceName": { "en": "Monk Wisdom AC", "fr": "CA Sagesse Moine" },
 *   "targetId": "combatStats.ac_normal",
 *   "value": "@attributes.stat_wis.derivedModifier",
 *   "type": "untyped",
 *   "conditionNode": { ... }
 * }
 * ```
 *
 * @example Situational modifier (Favoured Enemy: Orcs):
 * ```json
 * {
 *   "id": "mod_fe_orc_attack",
 *   "sourceId": "class_feature_ranger_favoured_enemy",
 *   "sourceName": { "en": "Favoured Enemy: Orc" },
 *   "targetId": "combatStats.attack_bonus",
 *   "value": 2,
 *   "type": "untyped",
 *   "situationalContext": "orc"
 * }
 * ```
 */
export interface Modifier {
  /**
   * Unique identifier for this specific modifier instance within its source Feature.
   * Used by the stacking engine to identify duplicates and by the UI breakdown modal.
   */
  id: ID;

  /**
   * The ID of the Feature that grants this modifier.
   * Used for UI attribution ("This +2 comes from your Ring of Protection").
   */
  sourceId: ID;

  /**
   * The localized display name of the source, shown in the breakdown modal.
   * Example: { en: "Ring of Protection +2", fr: "Anneau de protection +2" }
   */
  sourceName: LocalizedString;

  /**
   * The ID of the pipeline this modifier targets.
   *
   * CONVENTION:
   *   - Main attributes:  "stat_str", "stat_dex", "stat_con", "stat_int", "stat_wis", "stat_cha"
   *   - Combat stats:     "combatStats.ac_normal", "combatStats.bab", "combatStats.init"
   *   - Saves:            "saves.fort", "saves.ref", "saves.will"
   *   - Skills:           "skills.skill_climb", "skills.skill_jump"
   *   - Resources:        "resources.hp.maxValue" (via the maxPipelineId pointer)
   *   - Custom homebrew:  Any ID — the engine auto-creates the pipeline on first encounter.
   */
  targetId: ID;

  /**
   * The bonus or penalty value.
   *
   * - `number`: Applied directly (positive = bonus, negative = penalty).
   * - `string`: A Math Parser formula resolved at computation time.
   *             Must be a valid math expression with optional `@`-path variables.
   *             Examples:
   *               "@attributes.stat_wis.derivedModifier"   (Paladin/Monk cross-stat)
   *               "floor(@classLevels.class_soulknife / 4)" (scaling ability formula)
   *               "2 * @attributes.stat_str.derivedModifier" (two-handed damage)
   */
  value: number | string;

  /**
   * The D&D 3.5 modifier type, governing stacking behaviour.
   * See `ModifierType` in primitives.ts for full documentation.
   */
  type: ModifierType;

  /**
   * Optional: A logic tree evaluated at SHEET COMPUTATION TIME.
   * If present and evaluates to `false`, this modifier is completely ignored
   * and does not contribute to `totalBonus`.
   *
   * Examples of conditional modifiers:
   *   - Monk AC Bonus: only active when not wearing armour/shield/heavy load.
   *   - Rage Bonus: only active when the Barbarian is raging (has "raging" tag).
   *   - Shield Bonus from Mage Armor: only active if no physical shield equipped.
   *
   * If absent, the modifier is always active (when the parent Feature is active).
   */
  conditionNode?: LogicNode;

  /**
   * Optional: A context tag string for SITUATIONAL modifiers.
   *
   * WHY THIS DESIGN:
   *   Situational modifiers (like Favoured Enemy) must NOT appear on the static
   *   character sheet total — the character's attack bonus vs Orcs is NOT their
   *   general attack bonus. But the modifier must be available at dice-roll time.
   *
   *   Solution: if `situationalContext` is present, the engine routes this modifier
   *   to `StatisticPipeline.situationalModifiers` instead of `activeModifiers`.
   *   The Dice Engine then matches `situationalContext` against the roll's
   *   `RollContext.targetTags` to decide if it applies.
   *
   * Convention: use the same string as a tag that would appear in `@targetTags`.
   * Examples: "orc", "goblinoid", "attack_of_opportunity", "flanking", "evil"
   *
   * DUAL-GATING (BOTH conditionNode AND situationalContext may coexist):
   *   A modifier CAN have BOTH fields simultaneously. The engine handles this in two stages:
   *
   *   Stage 1 (SHEET TIME — `conditionNode` evaluation in Phase 0):
   *     The `conditionNode` is evaluated against the character's current state.
   *     If it FAILS: the modifier is completely ignored (not even added to situationalModifiers).
   *     If it PASSES: proceed to Stage 2.
   *
   *   Stage 2 (ROLL TIME — `situationalContext` matching):
   *     Because `situationalContext` is present, the modifier goes to `situationalModifiers`
   *     (not `activeModifiers`). It is only applied when the roll context includes the tag.
   *
   *   CANONICAL EXAMPLE — Barbarian Indomitable Will (ANNEXES.md section A.1.1):
   *     "+4 Will save vs Enchantment spells while Raging"
   *     - `conditionNode`: must have tag "rage" (sheet-time gating — only while raging)
   *     - `situationalContext`: "vs_enchantment" (roll-time gating — only vs enchantment)
   *     Both conditions must be met: the Barbarian must be RAGING and the roll must be
   *     AGAINST AN ENCHANTMENT for the +4 bonus to apply.
   */
  situationalContext?: string;
}

// =============================================================================
// STATISTIC PIPELINE — The universal stat container
// =============================================================================

/**
 * A fully resolved mathematical pipeline for any statistic.
 *
 * This is the shape of every entry in:
 *   - `Character.attributes`   (STR, DEX, CON, INT, WIS, CHA)
 *   - `Character.combatStats`  (AC normal/touch/flat, BAB, Initiative, Grapple)
 *   - `Character.saves`        (Fortitude, Reflex, Will)
 *   - Any custom homebrew stat (e.g., "stat_sanity", "stat_honour")
 *
 * The engine maintains two separate lists of modifiers:
 *   - `activeModifiers`:      Used to compute `totalBonus` and displayed on the sheet.
 *   - `situationalModifiers`: Never counted in totals; passed to the Dice Engine.
 *
 * SEPARATION OF ACTIVE VS SITUATIONAL:
 *   This is one of the most important architectural decisions in the engine.
 *   Without it, showing "+2 vs Orcs" on the sheet total would be misleading.
 *   With it, the sheet always shows the CHARACTER's true resting value,
 *   and situational bonuses only appear in the dice roll result.
 *
 * DERIVED MODIFIER (`derivedModifier`):
 *   Computed automatically by the engine from `totalValue` using the D&D 3.5 formula:
 *     derivedModifier = Math.floor((totalValue - 10) / 2)
 *   This is meaningful ONLY for the 6 main ability scores. For all other pipelines
 *   (AC, BAB, etc.), this field is 0 and has no functional meaning.
 *   It is NEVER stored in save files — always recomputed from `totalValue`.
 *
 * SETABSOLUTE OVERRIDE:
 *   If any `activeModifier` has `type: "setAbsolute"`, the engine ignores `baseValue`
 *   and all other modifiers. `totalValue` is set directly to the `setAbsolute` value.
 *   `derivedModifier` is still recomputed from this forced value.
 */
export interface StatisticPipeline {
  /**
   * The pipeline's unique identifier.
   * Example: "stat_str", "combatStats.ac_normal", "saves.fort"
   */
  id: ID;

  /**
   * Localized display label shown in the UI.
   * Example: { en: "Strength", fr: "Force" }
   */
  label: LocalizedString;

  /**
   * The base value BEFORE any modifiers are applied.
   *
   * For ability scores: the player-assigned base stat (e.g., 16 = STR 16 before items).
   * For saves/BAB: this is 0; the engine accumulates `base` type modifiers from class
   *               levelProgression entries instead.
   * For custom stats: typically 0 (start from nothing, build up from modifiers).
   *
   * This value IS stored in save files (it represents player choices or GM-set values).
   */
  baseValue: number;

  /**
   * Modifiers that are permanently active or conditionally active at SHEET TIME.
   *
   * The engine populates this list during DAG Phase 0 (flattening) by:
   *   1. Taking all modifiers from all active Features (after prerequisite checks).
   *   2. Evaluating each modifier's `conditionNode` (if present).
   *   3. Filtering OUT modifiers with `situationalContext` (those go to situationalModifiers).
   *
   * The stacking engine (`stackingRules.ts`) then resolves this list to compute `totalBonus`.
   */
  activeModifiers: Modifier[];

  /**
   * Modifiers that are ONLY applicable at DICE ROLL TIME.
   *
   * Populated by the engine from modifiers that have a `situationalContext` field.
   * Never included in `totalBonus`. Passed directly to `parseAndRoll()` for evaluation.
   *
   * The Dice Engine compares each modifier's `situationalContext` string against the
   * provided `RollContext.targetTags` array. If there's a match, the modifier's value
   * is added to `RollResult.situationalBonusApplied`.
   */
  situationalModifiers: Modifier[];

  /**
   * The net bonus from all applicable `activeModifiers`, after stacking rules.
   *
   * Computed by `stackingRules.ts`:
   *   - Same `type` (non-stackable): only the highest value among all modifiers
   *     of that type is included (e.g., two enhancement bonuses → take the larger).
   *   - Stackable types (dodge, circumstance, synergy, untyped): sum all values.
   *   - `multiplier` types: applied AFTER all additive bonuses.
   *   - `setAbsolute` types: override everything; no stacking even considered.
   *
   * Note: Can be negative (Net penalty. e.g., Strength damage from poison).
   */
  totalBonus: number;

  /**
   * The final computed value of this pipeline.
   * Formula: `totalValue = baseValue + totalBonus`
   * Exception: If any modifier has `type: "setAbsolute"`, `totalValue = setAbsolute value`.
   *
   * This is the value displayed on the character sheet as the "final" number.
   */
  totalValue: number;

  /**
   * The D&D 3.5 modifier derived from `totalValue`.
   * Formula: `Math.floor((totalValue - 10) / 2)`
   *
   * Only semantically meaningful for the 6 main ability scores.
   * For all other pipelines, this field is `0` by convention.
   *
   * NOT stored in save files; always recomputed by the engine.
   *
   * Examples:
   *   STR 10 → derivedModifier = 0
   *   STR 18 → derivedModifier = +4
   *   STR 7  → derivedModifier = -2
   *   STR 1  → derivedModifier = -5
   */
  derivedModifier: number;
}

// =============================================================================
// SKILL PIPELINE — Specialised pipeline for skills
// =============================================================================

/**
 * A pipeline specialized for skills, extending `StatisticPipeline`.
 *
 * WHY EXTEND?
 *   Skills share the same additive modifier mechanic as any other stat, but they
 *   have additional D&D 3.5-specific metadata:
 *     - A key ability score (e.g., DEX for Tumble, INT for Knowledge)
 *     - Invested ranks (the player's skill point spending decision)
 *     - Class skill status (affects cost-per-rank and max-rank cap)
 *     - Armour check penalty (for physical skills like Climb, Swim, Hide)
 *     - Trained-only flag (some skills cannot be used without at least 1 rank)
 *
 *   For skills, `baseValue` (from the parent interface) is NOT used for the total
 *   calculation. Instead, the engine uses: `ranks + keyAbilityModifier + totalBonus`.
 *   The `ranks` field replaces `baseValue` as the player-invested component.
 *
 * RANK STORAGE:
 *   `ranks` is the only skill field stored in save files (alongside `baseValue` which
 *   is kept for interface consistency but can be ignored by the skill computation).
 *
 * SYNERGY BONUSES:
 *   Some skills provide synergy bonuses to others when ranks reach 5 (e.g., 5 ranks
 *   in Tumble grants +2 to Balance checks). These are implemented as regular
 *   `Modifier` objects in the Feature's `grantedModifiers`, with a `conditionNode`
 *   like: `{ "@skills.skill_tumble.ranks": { ">=": 5 } }`.
 *   The engine evaluates them like any conditional modifier; no special handling needed.
 */
export interface SkillPipeline extends StatisticPipeline {
  /**
   * The ID of the ability score pipeline that this skill uses as its base modifier.
   * Example: "stat_dex" for Tumble, "stat_int" for Knowledge (Arcana).
   *
   * The engine reads `character.attributes[keyAbility].derivedModifier` during
   * DAG Phase 4 to compute the skill's base contribution from the ability score.
   */
  keyAbility: ID;

  /**
   * The number of skill ranks the player has invested in this skill.
   *
   * D&D 3.5 rank costs:
   *   - Class skill:       1 skill point per rank
   *   - Cross-class skill: 2 skill points per rank (max ranks = half of class skill max)
   *
   * Rank caps (per class skill status):
   *   - Class skill:       (character level + 3) maximum ranks
   *   - Cross-class skill: floor((character level + 3) / 2) maximum ranks
   *
   * This value IS stored in save files.
   */
  ranks: number;

  /**
   * Whether this skill counts as a class skill for the character's current class combination.
   *
   * The engine calculates this during DAG Phase 4 by taking the union of all
   * `classSkills` arrays from all active class Features (and domain/racial Features
   * that also declare classSkills). A skill is a class skill if it appears in ANY
   * of the active classes' classSkills arrays.
   *
   * Effect: determines rank cost (1 vs 2 points/rank) and maximum rank cap.
   */
  isClassSkill: boolean;

  /**
   * Whether the armour check penalty applies to this skill.
   *
   * D&D 3.5 armour check penalty affects physical skills like:
   *   Climb, Jump, Swim, Hide, Move Silently, Balance, Tumble, Escape Artist, etc.
   * It does NOT affect mental skills like Spellcraft, Knowledge (all), Diplomacy, etc.
   *
   * The penalty value is computed during DAG Phase 3 (as a combat stat pipeline)
   * and injected as a modifier into affected skills during Phase 4.
   */
  appliesArmorCheckPenalty: boolean;

  /**
   * Whether this skill can be used without any invested ranks.
   *
   * Most skills can be attempted untrained (e.g., Climb, Spot, Listen).
   * Some skills explicitly require training (e.g., Spellcraft, Disable Device,
   * Knowledge (all), Perform, and many psionic skills).
   * When `false`, the engine should warn the UI when ranks = 0.
   */
  canBeUsedUntrained: boolean;
}

// =============================================================================
// RESOURCE POOL — Depletable resources (HP, psi points, charges, etc.)
// =============================================================================

/**
 * A resource that can be depleted and restored.
 *
 * Design:
 *   Resource pools are intentionally separate from stat pipelines because they
 *   have a CURRENT VALUE that changes during play (combat rounds, spell use, etc.).
 *   A `StatisticPipeline` tracks a character's capabilities; a `ResourcePool` tracks
 *   their remaining capacity to exercise those capabilities.
 *
 * Examples of resource pools:
 *   - `resources.hp`           : Hit Points (current, temporary, max)
 *   - `resources.psi_points`   : Psionic power points (Psion, Wilder, etc.)
 *   - `resources.rage_rounds`  : Barbarian Rage rounds per day
 *   - `resources.turn_undead`  : Cleric Turn Undead uses per day
 *   - `resources.item_charges` : Charges on a wand, staff, or ring
 *
 * MAXIMUM VALUE VIA PIPELINE:
 *   The maximum is not stored directly — it is computed by a separate `StatisticPipeline`
 *   referenced by `maxPipelineId`. This allows the max to be dynamic:
 *     - HP max depends on CON modifier, which changes with Belt of Constitution.
 *     - Psi Points max depends on manifester level and key ability.
 *   When the referenced pipeline updates, the resource pool's effective max auto-updates
 *   because the DAG reads `maxPipelineId` to find the max at display time.
 *
 * TEMPORARY VALUES:
 *   `temporaryValue` is used for buffs like Temporary HP (from Aid Another, Heroism KO'd check, etc.).
 *   D&D 3.5 rule: temporary HP absorbs damage FIRST, before regular HP is reduced.
 *   The UI must implement this correctly (Phase 10.1).
 *
 * HOW STORED:
 *   `currentValue` and `temporaryValue` ARE stored in save files (they represent
 *   in-play state). `maxPipelineId` is stored as a pointer ID. The actual max is
 *   recomputed from the pipeline at load time.
 */
export interface ResourcePool {
  /**
   * Unique identifier for this resource pool.
   * Convention: "resources.<name>" (e.g., "resources.hp", "resources.psi_points")
   */
  id: ID;

  /**
   * Localized display label.
   * Example: { en: "Hit Points", fr: "Points de vie" }
   */
  label: LocalizedString;

  /**
   * The ID of the `StatisticPipeline` that computes this resource's MAXIMUM value.
   *
   * This pipeline is defined and computed in DAG Phase 3. For HP:
   *   "stat_max_hp" pipeline formula:
   *   sum of (hitDieResult[level] for each level) + (CON.derivedModifier × character level)
   *
   * The ResourcePool reads this pipeline's `totalValue` at display time to know the cap.
   */
  maxPipelineId: ID;

  /**
   * The character's current value of this resource.
   * Starts at the computed max on character creation or after a long rest.
   * Updated by the player (and by the GM via overrides) during play.
   *
   * For HP: Decreases when taking damage, increases when healed.
   * Note: current HP can go negative (unconscious/dying in D&D 3.5).
   */
  currentValue: number;

  /**
   * Temporary bonus value that absorbs depletion before `currentValue` is affected.
   *
   * D&D 3.5 rule for temporary HP:
   *   When taking damage, temporary HP is reduced FIRST.
   *   Temporary HP does not stack with itself (new temporary HP replaces old, unless
   *   the old is higher — per SRD). The engine/UI should enforce this rule.
   *
   * For psi points and other non-HP resources: temporarily restored capacity
   * (e.g., a partial restore from a psionic power). Usually 0.
   */
  temporaryValue: number;

  /**
   * The condition under which this resource naturally resets to its maximum.
   *
   * - `"long_rest"`:  D&D 3.5 "8 hours of restful sleep" (SRD standard for spells, HP).
   * - `"short_rest"`: Optional house rule (not default D&D 3.5 — typically for variants).
   * - `"encounter"`:  Resets at the start of each combat encounter (some class abilities).
   * - `"never"`:      Does not reset automatically (e.g., item charges, once-per-day abilities
   *                   on items, XP-spent powers). Requires an explicit action or rest mechanic.
   */
  resetCondition: 'short_rest' | 'long_rest' | 'encounter' | 'never';
}
